import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from './api'
import { useAuth } from './auth'
import { ErrorState, Loading } from './components'
import type { ArtworkType, Episode, Season, Show, Status } from './types'

const sections = ['featured', 'series', 'minisodes', 'songs']
const categories = ['adventure', 'folk', 'friendship', 'india', 'language', 'learning', 'maths', 'music', 'nature', 'reading', 'science', 'singalong', 'stories', 'travel', 'values']
const languages = ['en', 'hi']
const statuses: Status[] = ['draft', 'published', 'archived']
const message = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong. Please try again.'
const fieldError = (error: unknown) => error instanceof ApiError && error.status === 422 ? error.message : null

function StatusSelect({ value, onChange }: { value: Status; onChange: (value: Status) => void }) { return <select value={value} onChange={e => onChange(e.target.value as Status)}>{statuses.map(item => <option key={item}>{item}</option>)}</select> }
function PageTitle({ title, children }: { title: string; children?: React.ReactNode }) { return <div className="page-title"><h1>{title}</h1>{children}</div> }
function LifecycleBanner({ status, blockers = [] }: { status: Status; blockers?: string[] }) {
  if (status === 'published') return <aside className="lifecycle-banner ready"><b>Ready for catalogue publishing</b><p>This content is published and will be included the next time an admin publishes the catalogue.</p></aside>
  if (status === 'archived') return null
  return <aside className="lifecycle-banner draft"><b>Not ready for publishing</b><p>Complete the required content and artwork, then change the status to Published. Published content becomes eligible for the next catalogue publish.</p>{blockers.length > 0 && <><strong>To prepare this content:</strong><ul>{blockers.map(blocker => <li key={blocker}>{blocker}</li>)}</ul></>}</aside>
}
function episodeBlockers(episode: Pick<Episode, 'duration_seconds' | 'language' | 'artwork_types' | 'season_id'>, seasons: Season[]) {
  const blockers: string[] = []
  if (!episode.duration_seconds || episode.duration_seconds <= 0) blockers.push('Add duration')
  if (!languages.includes(episode.language)) blockers.push('Choose English or Hindi as the language')
  if (!seasons.some(season => season.id === episode.season_id)) blockers.push('Choose a valid season')
  ;(['poster', 'banner', 'thumbnail'] as ArtworkType[]).filter(type => !episode.artwork_types.includes(type)).forEach(type => blockers.push(`Upload a ${type}`))
  return blockers
}

export function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState('')
  const mutation = useMutation({ mutationFn: () => login(email, password), onSuccess: () => navigate('/shows') })
  if (user) return <Navigate to="/shows" replace />
  return <main className="login"><form onSubmit={e => { e.preventDefault(); mutation.mutate() }}><h1>Peblo CMS</h1><p>Sign in to manage content.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{mutation.error && <p className="form-error">{message(mutation.error)}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Signing in…' : 'Sign in'}</button></form></main>
}

export function ShowListPage() {
  const [offset, setOffset] = useState(0); const [search, setSearch] = useState(''); const [section, setSection] = useState(''); const [status, setStatus] = useState('')
  const query = useQuery({ queryKey: ['shows', offset], queryFn: () => api.shows(offset) })
  const filtered = useMemo(() => (query.data?.items ?? []).filter(show => (!search || `${show.title} ${show.slug}`.toLowerCase().includes(search.toLowerCase())) && (!section || show.section === section) && (!status || show.status === status)), [query.data, search, section, status])
  if (query.isLoading) return <Loading />; if (query.error) return <ErrorState error={query.error} retry={() => query.refetch()} />
  const page = query.data!
  return <><PageTitle title="Shows"><Link className="button" to="/shows/new">Create show</Link></PageTitle><p className="muted">Filters apply to this server-paginated page; the current API does not expose show search/filter parameters.</p><div className="filters"><input placeholder="Search this page" value={search} onChange={e => setSearch(e.target.value)} /><select value={section} onChange={e => setSection(e.target.value)}><option value="">All sections</option>{sections.map(item => <option key={item}>{item}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(item => <option key={item}>{item}</option>)}</select></div>{filtered.length === 0 ? <p className="state">No shows match this page.</p> : <table><thead><tr><th>Title</th><th>Section</th><th>Status</th><th /></tr></thead><tbody>{filtered.map(show => <tr key={show.id}><td><Link to={`/shows/${show.id}`}>{show.title}</Link><small>{show.slug}</small></td><td>{show.section ?? '—'}</td><td><span className={`pill ${show.status}`}>{show.status}</span></td><td><Link to={`/shows/${show.id}/edit`}>Edit</Link></td></tr>)}</tbody></table>}<div className="pager"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - page.limit))}>Previous</button><span>{offset + 1}–{Math.min(offset + page.limit, page.total)} of {page.total}</span><button disabled={offset + page.limit >= page.total} onClick={() => setOffset(offset + page.limit)}>Next</button></div></>
}

export function EpisodeListPage() {
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const query = useQuery({ queryKey: ['episodes'], queryFn: () => api.episodes() })
  const episodes = useMemo(() => (query.data?.items ?? []).filter(episode =>
    (!search || `${episode.title} ${episode.language} ${episode.content_group}`.toLowerCase().includes(search.toLowerCase())) &&
    (!status || episode.status === status)
  ), [query.data, search, status])

  if (query.isLoading) return <Loading />
  if (query.error) return <ErrorState error={query.error} retry={() => query.refetch()} />

  return <><PageTitle title="Episodes" /><div className="filters"><input placeholder="Search episodes" value={search} onChange={e => setSearch(e.target.value)} /><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(item => <option key={item}>{item}</option>)}</select></div>{episodes.length === 0 ? <p className="state">No episodes match.</p> : <table><thead><tr><th>Title</th><th>Language</th><th>Status</th><th>Show</th></tr></thead><tbody>{episodes.map(episode => <tr key={episode.id}><td>{episode.title}<small>S{episode.season_id} · E{episode.episode_number}</small></td><td>{episode.language}</td><td><span className={`pill ${episode.status}`}>{episode.status}</span></td><td><Link to={`/shows/${episode.show_id}`}>View show</Link></td></tr>)}</tbody></table>}</>
}

type ShowForm = { title: string; slug: string; synopsis: string; section: string; categories: string[]; status: Status }
const blankShow: ShowForm = { title: '', slug: '', synopsis: '', section: '', categories: [], status: 'draft' }
export function ShowFormPage() {
  const { showId } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const existing = useQuery({ queryKey: ['show', showId], queryFn: () => api.show(showId!), enabled: !!showId }); const [form, setForm] = useState<ShowForm>(blankShow)
  useEffect(() => { if (existing.data) setForm({ ...existing.data, synopsis: existing.data.synopsis ?? '', section: existing.data.section ?? '' }) }, [existing.data])
  const mutation = useMutation({ mutationFn: () => showId ? api.updateShow(Number(showId), { ...form, synopsis: form.synopsis || null, section: form.section || null }) : api.createShow({ ...form, synopsis: form.synopsis || null, section: form.section || null }), onSuccess: result => { queryClient.invalidateQueries({ queryKey: ['shows'] }); queryClient.invalidateQueries({ queryKey: ['show', showId] }); navigate(`/shows/${result.id}`) } })
  if (existing.isLoading) return <Loading />; if (existing.error) return <ErrorState error={existing.error} retry={() => existing.refetch()} />
  const update = <K extends keyof ShowForm>(key: K, value: ShowForm[K]) => setForm(old => ({ ...old, [key]: value }))
  const blockers = !form.section ? ['Choose a section'] : []
  return <><PageTitle title={showId ? 'Edit show' : 'Create show'} /><form className="form" onSubmit={e => { e.preventDefault(); mutation.mutate() }}><LifecycleBanner status={form.status} blockers={blockers} /><label>Title<input value={form.title} onChange={e => update('title', e.target.value)} required /></label><label>Slug<input pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug} onChange={e => update('slug', e.target.value)} required /><small>Lowercase letters, numbers, and hyphens only.</small></label><label>Synopsis<textarea value={form.synopsis} onChange={e => update('synopsis', e.target.value)} /></label><label>Section<select value={form.section} onChange={e => update('section', e.target.value)}><option value="">None</option>{sections.map(item => <option key={item}>{item}</option>)}</select></label><label>Content status<StatusSelect value={form.status} onChange={value => update('status', value)} /><small>Changing this to Published does not make it visible in the Viewer until an admin publishes the catalogue.</small></label><fieldset><legend>Categories</legend>{categories.map(category => <label className="check" key={category}><input type="checkbox" checked={form.categories.includes(category)} onChange={() => update('categories', form.categories.includes(category) ? form.categories.filter(item => item !== category) : [...form.categories, category])} />{category}</label>)}</fieldset>{mutation.error && <p className="form-error">{message(mutation.error)}</p>}<div><button disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save show'}</button><button type="button" className="secondary" onClick={() => navigate(-1)}>Cancel</button></div></form></>
}

export function ShowManagementPage() {
  const { user } = useAuth(); const { showId = '' } = useParams(); const queryClient = useQueryClient(); const [episodeFilter, setEpisodeFilter] = useState(''); const show = useQuery({ queryKey: ['show', showId], queryFn: () => api.show(showId) }); const seasons = useQuery({ queryKey: ['seasons', showId], queryFn: () => api.seasons(showId) }); const episodes = useQuery({ queryKey: ['episodes', showId], queryFn: () => api.episodes({ showId }) })
  const deleteShow = useMutation({ mutationFn: () => api.deleteShow(Number(showId)), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['shows'] }); location.assign('/shows') } })
  if (show.isLoading || seasons.isLoading || episodes.isLoading) return <Loading />; if (show.error) return <ErrorState error={show.error} retry={() => show.refetch()} />; if (seasons.error || episodes.error) return <ErrorState error={seasons.error ?? episodes.error} retry={() => { seasons.refetch(); episodes.refetch() }} />
  const visibleEpisodes = episodes.data!.items.filter(episode => !episodeFilter || `${episode.title} ${episode.language} ${episode.content_group}`.toLowerCase().includes(episodeFilter.toLowerCase()))
  return <><PageTitle title={show.data!.title}><Link className="button secondary" to={`/shows/${showId}/edit`}>Edit show</Link>{user?.role === 'admin' && <button className="danger" onClick={() => { if (confirm('Delete this show and its seasons and episodes?')) deleteShow.mutate() }}>Delete show</button>}</PageTitle><p>{show.data!.synopsis || 'No synopsis.'}</p><section><SeasonManager showId={Number(showId)} seasons={seasons.data!.items} /></section><section><div className="section-title"><h2>Episodes</h2><button onClick={() => document.getElementById('episode-form')?.scrollIntoView()}>Add episode</button></div><input placeholder="Filter episodes by title, language, or content group" value={episodeFilter} onChange={e => setEpisodeFilter(e.target.value)} />{visibleEpisodes.length === 0 ? <p className="state">No episodes match.</p> : <div className="cards">{visibleEpisodes.map(episode => <EpisodeCard key={episode.id} episode={episode} seasons={seasons.data!.items} />)}</div>}<EpisodeForm showId={Number(showId)} seasons={seasons.data!.items} /></section></>
}

function SeasonManager({ showId, seasons }: { showId: number; seasons: Season[] }) { const { user } = useAuth(); const queryClient = useQueryClient(); const [number, setNumber] = useState('1'); const add = useMutation({ mutationFn: () => api.createSeason(showId, Number(number)), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['seasons', String(showId)] }) }); const remove = useMutation({ mutationFn: api.deleteSeason, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['seasons', String(showId)] }) }); return <><div className="section-title"><h2>Seasons</h2><form className="inline" onSubmit={e => { e.preventDefault(); add.mutate() }}><input type="number" min="0" value={number} onChange={e => setNumber(e.target.value)} /><button disabled={add.isPending}>Add season</button></form></div><p className="muted">Season 0 is reserved for trailers.</p>{add.error && <p className="form-error">{message(add.error)}</p>}{seasons.length === 0 ? <p className="state">No seasons yet.</p> : <ul className="compact-list">{seasons.map(season => <li key={season.id}>Season {season.season_number} {user?.role === 'admin' && <button className="link danger-text" onClick={() => { if (confirm('Delete this season and its episodes?')) remove.mutate(season.id) }}>Delete</button>}</li>)}</ul>}</> }

function EpisodeForm({ showId, seasons }: { showId: number; seasons: Season[] }) { const queryClient = useQueryClient(); const [form, setForm] = useState({ season_id: seasons[0]?.id ?? 0, episode_number: 1, title: '', synopsis: '', duration_seconds: '', language: 'en', content_group: '', status: 'draft' as Status }); const mutation = useMutation({ mutationFn: () => api.createEpisode({ ...form, show_id: showId, duration_seconds: form.duration_seconds ? Number(form.duration_seconds) : null, status: form.status }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['episodes', String(showId)] }); setForm(old => ({ ...old, title: '', synopsis: '', content_group: '' })) } }); if (seasons.length === 0) return <p className="muted">Create a season before adding episodes.</p>; const blockers = !form.duration_seconds ? ['Add duration', 'Upload a poster, banner, and thumbnail after saving'] : ['Upload a poster, banner, and thumbnail after saving']; return <form id="episode-form" className="form compact" onSubmit={e => { e.preventDefault(); mutation.mutate() }}><h3>Add episode</h3><LifecycleBanner status={form.status} blockers={blockers} /><label>Season<select value={form.season_id} onChange={e => setForm({ ...form, season_id: Number(e.target.value) })}>{seasons.map(season => <option key={season.id} value={season.id}>Season {season.season_number}</option>)}</select></label><label>Episode number<input type="number" min="0" value={form.episode_number} onChange={e => setForm({ ...form, episode_number: Number(e.target.value) })} /></label><label>Title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} required /></label><label>Synopsis<textarea value={form.synopsis} onChange={e => setForm({ ...form, synopsis: e.target.value })} /></label><label>Duration (seconds)<input type="number" min="1" value={form.duration_seconds} onChange={e => setForm({ ...form, duration_seconds: e.target.value })} /><small>Required for published episodes.</small></label><label>Language<select value={form.language} onChange={e => setForm({ ...form, language: e.target.value })}>{languages.map(item => <option key={item}>{item}</option>)}</select></label><label>Content group<input value={form.content_group} onChange={e => setForm({ ...form, content_group: e.target.value })} required /><small>Language variants of one episode use the same content group.</small></label><label>Content status<StatusSelect value={form.status} onChange={status => setForm({ ...form, status })} /><small>Changing this to Published does not make it visible in the Viewer until an admin publishes the catalogue.</small></label>{mutation.error && <p className="form-error">{fieldError(mutation.error) ?? message(mutation.error)}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Add episode'}</button></form> }

function EpisodeCard({ episode, seasons }: { episode: Episode; seasons: Season[] }) { const { user } = useAuth(); const queryClient = useQueryClient(); const [editing, setEditing] = useState(false); const [form, setForm] = useState(episode); const update = useMutation({ mutationFn: () => api.updateEpisode(episode.id, { ...form, duration_seconds: form.duration_seconds || null }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['episodes', String(episode.show_id)] }); setEditing(false) } }); const remove = useMutation({ mutationFn: () => api.deleteEpisode(episode.id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['episodes', String(episode.show_id)] }) }); return <article className="card"><div className="section-title"><div><b>S{seasons.find(item => item.id === episode.season_id)?.season_number ?? '?'} · E{episode.episode_number}</b><h3>{episode.title}</h3><small>{episode.language} · {episode.content_group} · <span className={`pill ${episode.status}`}>{episode.status}</span></small></div><div><button className="link" onClick={() => setEditing(!editing)}>{editing ? 'Close' : 'Edit'}</button>{user?.role === 'admin' && <button className="link danger-text" onClick={() => { if (confirm('Delete this episode?')) remove.mutate() }}>Delete</button>}</div></div>{editing && <form className="form compact" onSubmit={e => { e.preventDefault(); update.mutate() }}><LifecycleBanner status={form.status} blockers={episodeBlockers(form, seasons)} /><label>Season<select value={form.season_id} onChange={e => setForm({ ...form, season_id: Number(e.target.value) })}>{seasons.map(item => <option key={item.id} value={item.id}>Season {item.season_number}</option>)}</select></label><label>Episode number<input type="number" min="0" value={form.episode_number} onChange={e => setForm({ ...form, episode_number: Number(e.target.value) })} /></label><label>Title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Duration (seconds)<input type="number" min="1" value={form.duration_seconds ?? ''} onChange={e => setForm({ ...form, duration_seconds: e.target.value ? Number(e.target.value) : null })} /></label><label>Language<select value={form.language} onChange={e => setForm({ ...form, language: e.target.value })}>{languages.map(item => <option key={item}>{item}</option>)}</select></label><label>Content group<input value={form.content_group} onChange={e => setForm({ ...form, content_group: e.target.value })} /></label><label>Content status<StatusSelect value={form.status} onChange={status => setForm({ ...form, status })} /><small>Changing this to Published does not make it visible in the Viewer until an admin publishes the catalogue.</small></label>{update.error && <p className="form-error">{message(update.error)}</p>}<button disabled={update.isPending}>{update.isPending ? 'Saving…' : 'Save episode'}</button></form>}<ArtworkSlots episode={episode} /></article> }

const artworkRequirements: Record<ArtworkType, string> = { poster: '600×900 · 2:3 · max 200 KB', banner: '1280×720 · 16:9 · max 200 KB', thumbnail: '640×360 · 16:9 · max 200 KB' }
function ArtworkSlots({ episode }: { episode: Episode }) { const queryClient = useQueryClient(); const [preview, setPreview] = useState<Record<string, string>>({}); const upload = useMutation({ mutationFn: ({ type, file }: { type: ArtworkType; file: File }) => api.uploadArtwork(episode.id, type, file), onSuccess: (artwork) => { setPreview(old => ({ ...old, [artwork.type]: artwork.url })); queryClient.invalidateQueries({ queryKey: ['episodes', String(episode.show_id)] }) } }); return <div className="artwork"><h4>Artwork</h4>{(Object.keys(artworkRequirements) as ArtworkType[]).map(type => <div className="artwork-slot" key={type}><b>{type}</b><small>{artworkRequirements[type]}</small>{episode.artwork_types.includes(type) ? <span className="success">Uploaded</span> : <span className="muted">Not uploaded</span>}<input type="file" accept="image/*" onChange={e => { const file = e.target.files?.[0]; if (!file) return; setPreview(old => ({ ...old, [type]: URL.createObjectURL(file) })); upload.mutate({ type, file }) }} />{preview[type] && <img src={preview[type]} alt={`${type} preview`} />}</div>)}{upload.error && <p className="form-error">{message(upload.error)}</p>}{upload.isPending && <p className="muted">Uploading artwork…</p>}</div> }

export function PublishPage() { const queryClient = useQueryClient(); const report = useQuery({ queryKey: ['validation-report'], queryFn: api.validationReport }); const runs = useQuery({ queryKey: ['publish-runs'], queryFn: api.publishRuns }); const publish = useMutation({ mutationFn: api.publish, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['validation-report'] }); queryClient.invalidateQueries({ queryKey: ['publish-runs'] }) } }); if (report.isLoading) return <Loading />; if (report.error) return <ErrorState error={report.error} retry={() => report.refetch()} />; const data = report.data!; return <><PageTitle title="Publish catalogue" /><section className={data.can_publish ? 'report ok' : 'report blocked'}><h2>{data.can_publish ? 'Ready to publish' : 'Publishing is blocked'}</h2><p>{data.can_publish ? 'All published content passes validation.' : `${data.total_issues} issue(s) must be fixed before publishing.`}</p>{!data.can_publish && data.shows.map(show => <div key={show.show_id} className="issue-group"><h3>{show.show_title}</h3>{show.issues.map(issue => <p key={issue.field}><b>{issue.field}:</b> {issue.message}</p>)}{show.episodes.map(episode => <div key={episode.episode_id}><h4>{episode.episode_title}</h4>{episode.issues.map(issue => <p key={issue.field}><b>{issue.field}:</b> {issue.message}</p>)}</div>)}</div>)}</section><button disabled={!data.can_publish || publish.isPending} onClick={() => publish.mutate()}>{publish.isPending ? 'Publishing…' : 'Publish catalogue'}</button>{!data.can_publish && <p className="muted">The button is disabled until every issue above is resolved.</p>}{publish.error && <p className="form-error">{message(publish.error)}</p>}{publish.data && <p className="success">Published {publish.data.show_count} shows and {publish.data.episode_count} episodes as {publish.data.catalogue_version}.</p>}<section className="publish-history"><h2>Publish history</h2>{runs.isLoading && <p className="muted">Loading publish history…</p>}{runs.error && <p className="form-error">{message(runs.error)}</p>}{runs.data?.length === 0 && <p className="muted">No catalogue publish attempts yet.</p>}{runs.data && runs.data.length > 0 && <table><thead><tr><th>Completed</th><th>Status</th><th>Catalogue version</th><th>Content</th><th>Details</th></tr></thead><tbody>{runs.data.map(run => <tr key={run.id}><td>{new Date(run.completed_at ?? run.started_at).toLocaleString()}</td><td><span className={`pill ${run.status.toLowerCase()}`}>{run.status.toLowerCase()}</span></td><td>{run.catalogue_version ?? '—'}</td><td>{run.status === 'success' ? `${run.show_count} shows · ${run.episode_count} episodes` : '—'}</td><td>{run.error_message ?? '—'}</td></tr>)}</tbody></table>}</section></> }
